from graphviz import Source
def pk_demo1():
    src = Source('strict graph { rankdir=LR; format = "png";'
             'splines=line; size = "4,2";'
             'A -- {B C D} -- {E F G} -- {H I} -- J;'
             'B -- A [taillabel = "2"  fontsize = "12"];'
             'C -- A [taillabel = "4"  fontsize = "12"];'
             'D -- A [taillabel = "3"  fontsize = "12"];'
             'E -- B [taillabel = "7" fontsize = "12"];'
             'F -- B [taillabel = "4" fontsize = "12"];'
             'G -- B [taillabel = "6" fontsize = "12"];'
             'E -- C [taillabel = "3" fontsize = "12"];'
             'F -- C [taillabel = "2" fontsize = "12"];'
             'G -- C [taillabel = "4" fontsize = "12"];'
             'E -- D [taillabel = "4" fontsize = "12"];'
             'F -- D [taillabel = "1" fontsize = "12"];'
             'G -- D [taillabel = "5" fontsize = "12"];'
             'H -- E [taillabel = "1" fontsize = "12"];'
             'I -- E [taillabel = "4" fontsize = "12"];'
             'H -- F [taillabel = "6" fontsize = "12"];'
             'I -- F [taillabel = "3" fontsize = "12"];'
             'H -- G [taillabel = "3" fontsize = "12"];'
             'I -- G [taillabel = "3" fontsize = "12"];'
             'J -- H [taillabel = "3" fontsize = "12"];'
             'J -- I [taillabel = "4" fontsize = "12"];'
             '}')
    return src

def pk_demo2():
    src1 = Source('strict graph { rankdir=LR; format = "png";'
             'splines=line; size = "4,2";'
             'B [label = "B(2)"];'
             'C [label = "C(4)"];'
             'D [label = "D(3)"];'
             'E [label = "E(7)"];'
             'F [label = "F(4)"];'
             'G [label = "G(8)"];'
             'H [label = "H(8)"];'
             'I [label = "I(7)"];'
             'J [label = "J(11)"];'
             'A -- {B C D} -- {E F G} -- {H I} -- J;'
             'B -- A [taillabel = "2"  fontsize = "12" color = "blue"];'
             'C -- A [taillabel = "4"  fontsize = "12" color = "blue"];'
             'D -- A [taillabel = "3"  fontsize = "12" color = "blue"];'
             'E -- B [taillabel = "7" fontsize = "12"];'
             'F -- B [taillabel = "4" fontsize = "12"];'
             'G -- B [taillabel = "6" fontsize = "12" color = "blue"];'
             'E -- C [taillabel = "3" fontsize = "12" color = "blue"];'
             'F -- C [taillabel = "2" fontsize = "12"];'
             'G -- C [taillabel = "4" fontsize = "12" color = "blue"];'
             'E -- D [taillabel = "4" fontsize = "12" color = "blue"];'
             'F -- D [taillabel = "1" fontsize = "12" color = "blue"];'
             'G -- D [taillabel = "5" fontsize = "12" color = "blue"];'
             'H -- E [taillabel = "1" fontsize = "12" color = "blue"];'
             'I -- E [taillabel = "4" fontsize = "12"];'
             'H -- F [taillabel = "6" fontsize = "12"];'
             'I -- F [taillabel = "3" fontsize = "12" color = "blue"];'
             'H -- G [taillabel = "3" fontsize = "12"];'
             'I -- G [taillabel = "3" fontsize = "12"];'
             'J -- H [taillabel = "3" fontsize = "12" color = "blue"];'
             'J -- I [taillabel = "4" fontsize = "12" color = "blue"];'
             '}')
    return src1
    
def pk_demo3():
    src2 = Source('strict graph { rankdir=LR; format = "png";'
             'splines=line; size = "4,2";'
             'B [label = "B(2)"];'
             'C [label = "C(4)"];'
             'D [label = "D(3)"];'
             'E [label = "E(7)"];'
             'F [label = "F(4)"];'
             'G [label = "G(8)"];'
             'H [label = "H(8)"];'
             'I [label = "I(7)"];'
             'J [label = "J(11)"];'
             'A -- {B C D} -- {E F G} -- {H I} -- J;'
             'B -- A [taillabel = "2"  fontsize = "12"];'
             'C -- A [taillabel = "4"  fontsize = "12" color = "red"];'
             'D -- A [taillabel = "3"  fontsize = "12" color = "red"];'
             'E -- B [taillabel = "7" fontsize = "12"];'
             'F -- B [taillabel = "4" fontsize = "12"];'
             'G -- B [taillabel = "6" fontsize = "12"];'
             'E -- C [taillabel = "3" fontsize = "12" color = "red"];'
             'F -- C [taillabel = "2" fontsize = "12"];'
             'G -- C [taillabel = "4" fontsize = "12"];'
             'E -- D [taillabel = "4" fontsize = "12" color = "red"];'
             'F -- D [taillabel = "1" fontsize = "12" color = "red"];'
             'G -- D [taillabel = "5" fontsize = "12"];'
             'H -- E [taillabel = "1" fontsize = "12" color = "red"];'
             'I -- E [taillabel = "4" fontsize = "12"];'
             'H -- F [taillabel = "6" fontsize = "12"];'
             'I -- F [taillabel = "3" fontsize = "12" color = "red"];'
             'H -- G [taillabel = "3" fontsize = "12"];'
             'I -- G [taillabel = "3" fontsize = "12"];'
             'J -- H [taillabel = "3" fontsize = "12" color = "red"];'
             'J -- I [taillabel = "4" fontsize = "12" color = "red"];'
             '}')
    return src2

def dtw1():
    bsp1 = Source('graph {'
                  'rankdir=LR; splines=line ; size="6,2";'
                  'subgraph  {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4};'
                  'a1 -- {b0 b1 b2 b3 b4};'
                  'a2 -- {b0 b1 b2 b3 b4};'
                  'a3 -- {b0 b1 b2 b3 b4};'
                  'a4 -- {b0 b1 b2 b3 b4};'
                  
                  'b0 -- {c0 c1 c2 c3 c4};'
                  'b1 -- {c0 c1 c2 c3 c4};'
                  'b2 -- {c0 c1 c2 c3 c4};'
                  'b3 -- {c0 c1 c2 c3 c4};'
                  'b4 -- {c0 c1 c2 c3 c4};'
                  
                  'c0 -- {d0 d1 d2 d3 d4};'
                  'c1 -- {d0 d1 d2 d3 d4};'
                  'c2 -- {d0 d1 d2 d3 d4};'
                  'c3 -- {d0 d1 d2 d3 d4};'
                  'c4 -- {d0 d1 d2 d3 d4};'

                  'd0 -- {e0 e1 e2 e3 e4};'
                  'd1 -- {e0 e1 e2 e3 e4};'
                  'd2 -- {e0 e1 e2 e3 e4};'
                  'd3 -- {e0 e1 e2 e3 e4};'
                  'd4 -- {e0 e1 e2 e3 e4};'

                  'e0 -- {f0 f1 f2 f3 f4};'
                  'e1 -- {f0 f1 f2 f3 f4};'
                  'e2 -- {f0 f1 f2 f3 f4};'
                  'e3 -- {f0 f1 f2 f3 f4};'
                  'e4 -- {f0 f1 f2 f3 f4};'
                  '}')
    return bsp1

def dtw2():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- b0;'
                  'a0 -- {b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1};'
                  'a1 -- {b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2};'
                  'a2 -- {b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3};'
                  'a3 -- b4 [ style=invis ];'
                  'a4 -- {b0 b1 b2 b3 b4};'
                  
                  'b0 -- c0;'
                  'b0 -- {c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1};'
                  'b1 -- {c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c0 c1 c2 c3};'
                  'b3 -- c4 [ style=invis ];'
                  'b4 -- {c0 c1 c2 c3 c4};'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d0 d1 d2 d3};'
                  'c3 -- d4 [ style=invis ];'
                  'c4 -- {d0 d1 d2 d3 d4};'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1 e2};'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e0 e1 e2 e3};'
                  'd3 -- e4 [ style=invis ];'
                  'd4 -- {e0 e1 e2 e3 e4};'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- {f0 f1};'
                  'e1 -- {f2 f3 f4} [ style=invis ];'
                  'e2 -- {f0 f1 f2};'
                  'e2 -- {f3 f4} [ style=invis ];'
                  'e3 -- {f0 f1 f2 f3};'
                  'e3 -- f4 [ style=invis ];'
                  'e4 -- {f0 f1 f2 f3 f4};'
                 '}')
    return bsp2


def dtw3():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a4 -- {b0 b1 b2 b3 b4};'
                  
                  'b0 -- c0;'
                  'b0 -- {c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1};'
                  'b1 -- {c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c0 c1 c2 c3};'
                  'b3 -- c4 [ style=invis ];'
                  'b4 -- {c0 c1 c2 c3 c4};'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d0 d1 d2 d3};'
                  'c3 -- d4 [ style=invis ];'
                  'c4 -- {d0 d1 d2 d3 d4};'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1 e2};'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e0 e1 e2 e3};'
                  'd3 -- e4 [ style=invis ];'
                  'd4 -- {e0 e1 e2 e3 e4};'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- f0;'
                  'e1 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e2 -- f0;'
                  'e2 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e3 -- f0;'
                  'e3 -- {f1 f2 f3 f4 } [ style=invis ];'
                  'e4 -- f0;'
                  'e4 -- {f1 f2 f3 f4} [ style=invis ];'
                 '}')
    return bsp2

def dtw4():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a4 -- {b2 b3 b4};'
                  'a4 -- {b0 b1} [ style=invis ];'
                  
                  'b0 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c1 c2 c3};'
                  'b3 -- {c0 c4} [ style=invis ];'
                  'b4 -- {c2 c3 c4};'
                  'b4 -- {c0 c1} [ style=invis ];'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d1 d2 d3};'
                  'c3 -- {d0 d4} [ style=invis ];'
                  'c4 -- {d2 d3 d4};'
                  'c4 -- {d0 d1} [ style=invis ];'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1 e2};'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e1 e2};'
                  'd3 -- {e0 e3 e4} [ style=invis ];'
                  'd4 -- e2;'
                  'd4 -- {e0 e1 e3 e4} [ style=invis ];'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- f0;'
                  'e1 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e2 -- f0;'
                  'e2 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e3 -- {f0 f1 f2 f3 f4 } [ style=invis ];'
                  'e4 -- {f0 f1 f2 f3 f4} [ style=invis ];'
                 '}')
    return bsp2

def dtw5():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a4 -- {b2 b3 b4};'
                  'a4 -- {b0 b1} [ style=invis ];'
                  
                  'b0 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c1 c2 c3};'
                  'b3 -- {c0 c4} [ style=invis ];'
                  'b4 -- {c2 c3 c4};'
                  'b4 -- {c0 c1} [ style=invis ];'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d1 d2 d3};'
                  'c3 -- {d0 d4} [ style=invis ];'
                  'c4 -- {d2 d3 d4};'
                  'c4 -- {d0 d1} [ style=invis ];'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1 e2};'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e1 e2};'
                  'd3 -- {e0 e3 e4} [ style=invis ];'
                  'd4 -- e2;'
                  'd4 -- {e0 e1 e3 e4} [ style=invis ];'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- f0;'
                  'e1 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e2 -- f0;'
                  'e2 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e3 -- {f0 f1 f2 f3 f4 } [ style=invis ];'
                  'e4 -- {f0 f1 f2 f3 f4} [ style=invis ];'
                 '}')
    return bsp2

def dtw6():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                 'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a4 -- {b2 b3 b4};'
                  'a4 -- {b0 b1} [ style=invis ];'
                  
                  'b0 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c1 c2 c3};'
                  'b3 -- {c0 c4} [ style=invis ];'
                  'b4 -- {c2 c3 c4};'
                  'b4 -- {c0 c1} [ style=invis ];'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d1 d2 d3};'
                  'c3 -- {d0 d4} [ style=invis ];'
                  'c4 -- {d2 d3 d4};'
                  'c4 -- {d0 d1} [ style=invis ];'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1 e2};'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e1 e2};'
                  'd3 -- {e0 e3 e4} [ style=invis ];'
                  'd4 -- e2;'
                  'd4 -- {e0 e1 e3 e4} [ style=invis ];'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- f0;'
                  'e1 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e2 -- f0;'
                  'e2 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e3 -- {f0 f1 f2 f3 f4 } [ style=invis ];'
                  'e4 -- {f0 f1 f2 f3 f4} [ style=invis ];'
                 '}')
    return bsp2

def dtw7():
    bsp2 = Source('graph {'
                  'rankdir=LR; splines=line;  size="6,2";'
                  'subgraph "a" {rank = same;'
                  ' a0 [label = "1/5"];'
                  ' a1 [label = "1/4"];'
                  ' a2 [label = "1/3"];'
                  ' a3 [label = "1/2"];'
                  ' a4 [label = "1/1"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' b0 [label = "2/5"];'
                  ' b1 [label = "2/4"];'
                  ' b2 [label = "2/3"];'
                  ' b3 [label = "2/2"];'
                  ' b4 [label = "2/1"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' c0 [label = "3/5"];'
                  ' c1 [label = "3/4"];'
                  ' c2 [label = "3/3"];'
                  ' c3 [label = "3/2"];'
                  ' c4 [label = "3/1"];'
                  'c0 -- c1 -- c2 -- c3 -- c4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' d0 [label = "4/5"];'
                  ' d1 [label = "4/4"];'
                  ' d2 [label = "4/3"];'
                  ' d3 [label = "4/2"];'
                  ' d4 [label = "4/1"];'
                  'd0 -- d1 -- d2 -- d3 -- d4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' e0 [label = "5/5"];'
                  ' e1 [label = "5/4"];'
                  ' e2 [label = "5/3"];'
                  ' e3 [label = "5/2"];'
                  ' e4 [label = "5/1"];'
                  'e0 -- e1 -- e2 -- e3 -- e4 [ style=invis ];}'
                  'subgraph  {rank = same;'
                  ' f0 [label = "6/5"];'
                  ' f1 [label = "6/4"];'
                  ' f2 [label = "6/3"];'
                  ' f3 [label = "6/2"];'
                  ' f4 [label = "6/1"];'
                  'f0 -- f1 -- f2 -- f3 -- f4 [ style=invis ];}'
                  'a0 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a1 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a2 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a3 -- {b0 b1 b2 b3 b4} [ style=invis ];'
                  'a4 -- {b2 b4};'
                  'a4 -- b3 [color="red"];'
                  'a4 -- {b0 b1} [ style=invis ];'
                  
                  'b0 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b1 -- {c0 c1 c2 c3 c4} [ style=invis ];'
                  'b2 -- {c0 c1 c2};'
                  'b2 -- {c3 c4} [ style=invis ];'
                  'b3 -- {c1 c2};'
                  'b3 -- c3 [color="red"];'
                  'b3 -- {c0 c4} [ style=invis ];'
                  'b4 -- {c2 c3 c4};'
                  'b4 -- {c0 c1} [ style=invis ];'
                  
                  'c0 -- d0;'
                  'c0 -- {d1 d2 d3 d4} [ style=invis ];'
                  'c1 -- {d0 d1};'
                  'c1 -- {d2 d3 d4} [ style=invis ];'
                  'c2 -- {d0 d1 d2};'
                  'c2 -- {d3 d4} [ style=invis ];'
                  'c3 -- {d1 d3};'
                  'c3 -- d2 [color="red"];'
                  'c3 -- {d0 d4} [ style=invis ];'
                  'c4 -- {d2 d3 d4};'
                  'c4 -- {d0 d1} [ style=invis ];'

                  'd0 -- e0;'
                  'd0 -- {e1 e2 e3 e4} [ style=invis ];'
                  'd1 -- {e0 e1};'
                  'd1 -- {e2 e3 e4} [ style=invis ];'
                  'd2 -- {e0 e1};'
                  'd2 -- e2 [color="red"];'
                  'd2 -- {e3 e4} [ style=invis ];'
                  'd3 -- {e1 e2};'
                  'd3 -- {e0 e3 e4} [ style=invis ];'
                  'd4 -- e2;'
                  'd4 -- {e0 e1 e3 e4} [ style=invis ];'

                  'e0 -- f0;'
                  'e0 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e1 -- f0;'
                  'e1 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e2 -- f0 [color="red"];'
                  'e2 -- {f1 f2 f3 f4} [ style=invis ];'
                  'e3 -- {f0 f1 f2 f3 f4 } [ style=invis ];'
                  'e4 -- {f0 f1 f2 f3 f4} [ style=invis ];'
                 '}')
    return bsp2

def dtw8():
    bsp2 = Source('graph {'
                  'splines=line;  size="6,1";'
                  'subgraph "test" {rank = same;'
                  ' a0 [label = "n"];'
                  ' a1 [label = "i:"];'
                  ' a2 [label = "i:"];'
                  ' a3 [label = "z"];'
                  ' a4 [label = "z"];'
                  ' a5 [label = "n"];'
                  'a0 -- a1 -- a2 -- a3 -- a4 [ style=invis ];}'
                  'subgraph "ref" {rank = same;'
                  ' b0 [label = "n"];'
                  ' b1 [label = "i:"];'
                  ' b2 [label = "z"];'
                  ' b3 [label = "@"];'
                  ' b4 [label = "n"];'
                  'b0 -- b1 -- b2 -- b3 -- b4 [ style=invis ];}'
                  'a5 -- b4;'
                  'a4 -- b2;'
                  'a3 -- b2;'
                  'a2 -- b1;'
                  'a1 -- b1;'
                  'a0 -- b0'
                 '}')
    return bsp2


def trellis():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "0" color="red"];'
                  ' a1 [label = "0" color="red"];'
                  ' a2 [label = "0" color="red"];'
                  ' a3 [label = "0" color="red"];'
                  ' a4 [label = "0" color="red"];'
                  ' b0 [label = "1" color="red"];'
                  ' b1 [label = "1" color="red"];'
                  ' b2 [label = "1" color="red"];'
                  ' b3 [label = "1" color="red"];'
                  ' b4 [label = "1" color="red"];'
                  ' start  -- {a0 b0};'
                  '{a0 b0} -- {a1 b1};'
                  '{a1 b1} -- {a2 b2};'
                  '{a2 b2} -- {a3 b3};'
                  '{a3 b3} -- {a4 b4};'
                  '{a4 b4} -- ende;'
                '}')
    return bsp1

def trellis_pw():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "0.6" color="red"];'
                  ' a1 [label = "0.288" color="red"];'
                  ' a2 [label = "0.02448" color="red"];'
                  ' a3 [label = "0.0119232" color="red"];'
                  ' a4 [label = "0.0012839" color="red"];'
                  ' b0 [label = "0" color="red"];'
                  ' b1 [label = "0.024" color="red"];'
                  ' b2 [label = "0.0336" color="red"];'
                  ' b3 [label = "0.0055008" color="red"];'
                  ' b4 [label = "0.00229248" color="red"];'
                  ' start  -- {a0 b0};'
                  '{a0 b0} -- {a1 b1};'
                  '{a1 b1} -- {a2 b2};'
                  '{a2 b2} -- {a3 b3};'
                  '{a3 b3} -- {a4 b4};'
                  '{a4 b4} -- ende;'
                '}')
    return bsp1

def trellis_vit():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "0.6" color="red"];'
                  ' a1 [label = "0.288" color="red"];'
                  ' a2 [label = "0.02304" color="red"];'
                  ' a3 [label = "0.0055296" color="red"];'
                  ' a4 [label = "0.000442368" color="red"];'
                  ' b0 [label = "0" color="red"];'
                  ' b1 [label = "0.024" color="red"];'
                  ' b2 [label = "0.0288" color="red"];'
                  ' b3 [label = "0.003456" color="red"];'
                  ' b4 [label = "0.0006912" color="red"];'
                  ' start  -- {a0 b0};'
                  'a0 -- a1 [color="red"];'
                  'a0 -- b1  [style="dotted"];'
                  'b0 -- {a1 b1} [style="dotted"];'
                  'a1 -- a2 [style="dotted"];'
                  'a1 -- b2 [color="red"];'
                  'b1 -- {a2 b2} [style="dotted"];'
                  'a2 -- {a3 b3} [style="dotted"];'
                  'b2 -- a3 [style="dotted"];'
                  'b2 -- b3 [color="red"];'
                  'a3 -- {a4 b4} [style="dotted"];'
                  'b3 -- a4 [style="dotted"];'
                  'b3 -- b4 [color="red"];'
                  '{a4 b4} -- ende;'
                '}')
    return bsp1

def trellis_alpha():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "0.6" color="red"];'
                  ' a1 [label = "0.288" color="red"];'
                  ' a2 [label = "0.02448" color="red"];'
                  ' a3 [label = "0.0119232" color="red"];'
                  ' a4 [label = "0.0012839" color="red"];'
                  ' b0 [label = "0" color="red"];'
                  ' b1 [label = "0.024" color="red"];'
                  ' b2 [label = "0.0336" color="red"];'
                  ' b3 [label = "0.0055008" color="red"];'
                  ' b4 [label = "0.00229248" color="red"];'
                  ' start  -- {a0 b0} [style="dotted"];'
                  '{a0 b0} -- {a1 b1} [style="dotted"];'
                  '{a1 b1} -- {a2 b2} [style="dotted"];'
                  '{a2 b2} -- {a3 b3} [style="dotted"];'
                  '{a3 b3} -- {a4 b4} [style="dotted"];'
                  '{a4 b4} -- ende [style="dotted"];'
                '}')
    return bsp1

def trellis_beta():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "0.00596064" color="red"];'
                  ' a1 [label = "0.011064" color="red"];'
                  ' a2 [label = "0.0588" color="red"];'
                  ' a3 [label = "0.18" color="red"];'
                  ' a4 [label = "1" color="red"];'
                  ' b0 [label = "0.00528288" color="red"];'
                  ' b1 [label = "0.016248" color="red"];'
                  ' b2 [label = "0.0636" color="red"];'
                  ' b3 [label = "0.26" color="red"];'
                  ' b4 [label = "1" color="red"];'
                  ' start  -- {a0 b0} [style="dotted"];'
                  '{a0 b0} -- {a1 b1} [style="dotted"];'
                  '{a1 b1} -- {a2 b2} [style="dotted"];'
                  '{a2 b2} -- {a3 b3} [style="dotted"];'
                  '{a3 b3} -- {a4 b4} [style="dotted"];'
                  '{a4 b4} -- ende [style="dotted"];'
                '}')
    return bsp1

def trellis_gamma():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' a0 [label = "1" color="red"];'
                  ' a1 [label = "0.89096473" color="red"];'
                  ' a2 [label = "0.40248027" color="red"];'
                  ' a3 [label = "0.60009663" color="red"];'
                  ' a4 [label = "0.35899501" color="red"];'
                  ' b0 [label = "0" color="red"];'
                  ' b1 [label = "0.10903527" color="red"];'
                  ' b2 [label = "0.59751973" color="red"];'
                  ' b3 [label = "0.39990337" color="red"];'
                  ' b4 [label = "0.64100499" color="red"];'
                  ' start  -- {a0 b0} [style="dotted"];'
                  '{a0 b0} -- {a1 b1} [style="dotted"];'
                  '{a1 b1} -- {a2 b2} [style="dotted"];'
                  '{a2 b2} -- {a3 b3} [style="dotted"];'
                  '{a3 b3} -- {a4 b4} [style="dotted"];'
                  '{a4 b4} -- ende [style="dotted"];'
                '}')
    return bsp1

def trellis_xi():
    bsp1 = Source('graph { rankdir= LR;'
                  'splines=line ; size="10";'
                  ' start0 [label = "start"];'
                  ' a0 [label = "0.89096473" color="red"];'
                  ' a1 [label = "0.37880496" color="red"];'
                  ' a2 [label = "0.29569979" color="red"];'
                  ' a3 [label = "0.26670962" color="red"];'
                  ' a4 [label = "0.287196" color="red"];'
                  ' b0 [label = "0.10903527" color="red"];'
                  ' b1 [label = "0.51215977" color="red"];'
                  ' b2 [label = "0.10678048" color="red"];'
                  ' b3 [label = "0.33338702" color="red"];'
                  ' b4 [label = "0.071799" color="red"];'
                  ' ende0 [label = "ende"];'

                  ' start1 [label = "start"];'
                  ' a01 [label = "0" color="red"];'
                  ' a11 [label = "0.02367531" color="red"];'
                  ' a21 [label = "0.30439684" color="red"];'
                  ' a31 [label = "0.09228539" color="red"];'
                  ' a41 [label = "0.384603" color="red"];'
                  ' b01 [label = "0" color="red"];'
                  ' b11 [label = "0.08535996" color="red"];'
                  ' b21 [label = "0.29312289" color="red"];'
                  ' b31 [label = "0.30761797" color="red"];'
                  ' b41 [label = "0.256402" color="red"];'
                  ' ende1 [label = "ende"];'

                  ' start0   -- {a0 b0} [style="dotted"];'
                  '{a0 b0} -- {a1 b1} [style="dotted"];'
                  '{a1 b1} -- {a2 b2} [style="dotted"];'
                  '{a2 b2} -- {a3 b3} [style="dotted"];'
                  '{a3 b3} -- {a4 b4} [style="dotted"];'
                  '{a4 b4} -- ende0 [style="dotted"];'
                  
                  ' start1   -- {a01 b01} [style="dotted"];'
                  '{a01 b01} -- {a11 b11} [style="dotted"];'
                  '{a11 b11} -- {a21 b21} [style="dotted"];'
                  '{a21 b21} -- {a31 b31} [style="dotted"];'
                  '{a31 b31} -- {a41 b41} [style="dotted"];'
                  '{a41 b41} -- ende1 [style="dotted"];'
                '}')
    return bsp1
