from graphviz import Source
def hmm_demo1():
    src = Source('strict digraph {size = "4,2";'
             'node [shape = circle];'
             'A [label = "rainy"];'
             'B [label = "sunny"];'
             'C [label = "walk"];'
             'D [label = "shop"];'
             'E [label = "clean"];'
             'subgraph {rank=same;'
                 'A -> B };'
             'subgraph {rank=same;'
                 'C -> D -> E [style=invis]};'
             'A -> {A B} [arrowhead=vee arrowsize=0.5];'
             'B -> {A B} [arrowhead=vee arrowsize=0.5];'
             'rankdir=TD;'
             'A -> C [style=dashed color=red arrowhead=vee arrowsize=0.5]'
             'A -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5]'
             'A -> E [style=dashed color=green arrowhead=vee arrowsize=0.5]'
             'B -> C [style=dashed color=red arrowhead=vee arrowsize=0.5]'
             'B -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5]'
             'B -> E [style=dashed color=green arrowhead=vee arrowsize=0.5]'
             '}')
    return src

def hmm_demo2():
    src = Source('strict digraph {size = "4,2";'
             'node [shape = circle];'
             'A [label = "rainy"];'
             'B [label = "sunny"];'
             'C [label = "walk"];'
             'D [label = "shop"];'
             'E [label = "clean"];'
             'subgraph {rank=same;'
                 'A -> B };'
             'subgraph {rank=same;'
                 'C -> D -> E [style=invis]};'
             'A -> A [arrowhead=vee arrowsize=0.5 taillabel=0.4 fontsize=12];'
             'A -> B [arrowhead=vee arrowsize=0.5 taillabel=0.6 fontsize=12];'
             'B -> A [arrowhead=vee arrowsize=0.5 taillabel=0.2 fontsize=12];'
             'B -> B [arrowhead=vee arrowsize=0.5 taillabel=0.8 fontsize=12];'
             'rankdir=TD;'
             'A -> C [style=dashed color=red arrowhead=vee arrowsize=0.5 headlabel=0.2 fontsize=12]'
             'A -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5 headlabel=0.3 fontsize=12]'
             'A -> E [style=dashed color=green arrowhead=vee arrowsize=0.5 headlabel=0.5 fontsize=12]'
             'B -> C [style=dashed color=red arrowhead=vee arrowsize=0.5 headlabel=0.6 fontsize=12]'
             'B -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5 headlabel=0.3 fontsize=12]'
             'B -> E [style=dashed color=green arrowhead=vee arrowsize=0.5 headlabel=0.1 fontsize=12]'
             '}')
    return src

def hmm_demo3():
    src = Source('strict digraph {size = "4,3";'
             '0 [label=Start shape=doublecircle]'
             'node [shape = circle];'
             'A [label = "rainy"];'
             'B [label = "sunny"];'
             'C [label = "walk"];'
             'D [label = "shop"];'
             'E [label = "clean"];'
             '0 -> A [arrowhead=vee arrowsize=0.5 label=0 fontsize=12];'
             '0 -> B [arrowhead=vee arrowsize=0.5 label=1 fontsize=12];'
             'subgraph {rank=same;'
                 'A -> B };'
             'subgraph {rank=same;'
                 'C -> D -> E [style=invis]};'
             'A -> A [arrowhead=vee arrowsize=0.5 taillabel=0.4 fontsize=12];'
             'A -> B [arrowhead=vee arrowsize=0.5 label=0.6 fontsize=12];'
             'B -> A [arrowhead=vee arrowsize=0.5 label=0.2 fontsize=12];'
             'B -> B [arrowhead=vee arrowsize=0.5 label=0.8 fontsize=12];'
             'rankdir=TD;'
             'A -> C [style=dashed color=red arrowhead=vee arrowsize=0.5 headlabel=0.2 fontsize=12]'
             'A -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5 headlabel=0.3 fontsize=12]'
             'A -> E [style=dashed color=green arrowhead=vee arrowsize=0.5 headlabel=0.5 fontsize=12]'
             'B -> C [style=dashed color=red arrowhead=vee arrowsize=0.5 headlabel=0.6 fontsize=12]'
             'B -> D [style=dashed color=blue arrowhead=vee arrowsize=0.5 headlabel=0.3 fontsize=12]'
             'B -> E [style=dashed color=green arrowhead=vee arrowsize=0.5 headlabel=0.1 fontsize=12]'
             '}')
    return src

def hmm_demo5():
    src = Source('strict digraph {size = "6,4"; rankdir=LR;'
             'B1 [label = "sunny(0.6)"];'
             '{subgraph  {rankdir=LR;'
                  ' A2 [label = "rainy"];'
                  ' A3 [label = "rainy(0.0288)"];'
                  ' A4 [label = "rainy(0.003456)"];'
                  ' A5 [label = "rainy(0.0006912)"];'
                  'A2 -> A3 [ style=invis ];'
                  'A3 -> A4;'
                  'A4 -> A5;}'
             'subgraph  {rankdir=LR;'
                  ' B2 [label = "sunny(0.288)"];'
                  ' B3 [label = "sunny"];'
                  ' B4 [label = "sunny"];'
                  ' B5 [label = "sunny"];'
                  'B2 -> B3 -> B4 -> B5 [ style=invis ];}}'
             'B1 -> A2 [ style=invis ];'
             'B1 -> B2;'
             'B2 -> A3;'
             '}')
    return src

def hmm_demo4():
    src = Source('strict digraph {size = "4,3"; rankdir=LR;'
             'B1 [label = "sunny"];'
             'A2 [label = "rainy"];'
             'B2 [label = "sunny"];'
             'A3 [label = "rainy"];'
             'B3 [label = "sunny"];'
             'A4 [label = "rainy"];'
             'B4 [label = "sunny"];'
             'A5 [label = "rainy"];'
             'B5 [label = "sunny"];'
             'B1 -> {A2 B2}'
             'A2 -> {A3 B3}'
             'B2 -> {A3 B3}'
             'A3 -> {A4 B4}'
             'B3 -> {A4 B4}'
             'A4 -> {A5 B5}'
             'B4 -> {A5 B5}'
             '}')
    return src

def hmm_a5_7():
    src = Source('strict digraph {size = "4,2"; rankdir=LR;'
             'node [shape = circle];'
             'A [label = "A"];'
             'B [label = "B"];'
             'C [label = "C"];'
             'A -> {A B} [arrowhead=vee arrowsize=0.5];'
             'B -> {B C} [arrowhead=vee arrowsize=0.5];'
             'C -> C [arrowhead=vee arrowsize=0.5];'
             '}')
    return src
